### ISSUE TITLE
[Information] Now the default theme for my invidious instance invidious.nerdvpn.de

### ISSUE THREAD

**Issue by Sommerwiesel** [Tsyron/Invidious-Theme#2]
Heya,
just letting you know that I decided to modify and implement your theme as the default theme for my Invidious instance invidious.nerdvpn.de.

https://github.com/Sommerwiesel/invidious/tree/main/assets/css

Since you've not added any LICENSE information and thus no restrictions, I hope you're okay with this.
I have credited you and your repo in the commit.

Amazing theme and greetings from Germany,
Marvin

**Comment by Tsyron** [comment]
Hello, 
Thanks for letting me know, I'm glad you like it!
there is a license but it's GPLv3 so it's free to use :)

Thank you & greetings from Belgium
Alex
